### ISSUE TITLE
Separating cells based on color

### ISSUE THREAD

**Issue by mahati-acog** [immunogenomics/cna#13]
I was trying to get cells (with cell ids) that belong to red, blue and grey regions separately after cna association. I understand the color that is plotted is based on the ncorr values of each cell. I could not understand -

- [ ] how to get the cells in grey region. 
- [ ] Is ncorrs>0.0 red and ncorrs<0.0 blue? Is this logic right?

**Comment by rumker** [comment]
Hi there, we are happy to clarify your plotting question!

You are correct that our standard red/blue/grey plots of the association test results threshold each cell into a color/group based on the `ncorrs` value of the corresponding neighborhood anchored at that cell. We typically distinguish the expanded (red) and depleted (blue) populations as those cells _whose `ncorrs` values pass a selected FDR threshold for local significance_. The easiest places to check for thresholds are (where `res` is the result object from `cna.tl.association`): `res.fdr_5p_t` — which indicates the absolute value of ncorrs beyond which neighborhoods pass FDR 5%, and `res.fdr_10p_t` — which indicates the absolute value of ncorrs beyond which neighborhoods pass FDR 10%.  A full table of each FDR and the corresponding threshold value for ncorrs can be found in `res.fdrs`.  This table also indicates for each possible FDR threshold the total number of neighborhoods that pass that threshold.

To get your expanded population of cells (red) you'd take all cells with `ncorrs > res.fdr_5p_t` and likewise to get your depleted (blue) population you'd take all cells with with `ncorrs < -res.fdr_5p_t` (with values less than negative `res.fdr_5p_t`), if you were choosing to threshold at FDR 5%. Notably, if no neighborhood-scale associations rise to an FDR 5% level, then `res.fdr_5p_t` will be empty, and likewise if no neighborhood-scale associations rise to a FDR 10% level, then `res.fdr_10p_t` will be empty. If these two values are both empty, you could look at the full table `res.fdrs` to explore whether any local associations come close (e.g. FDR ~11%) or not.  The grey cells would be the remainder that are not included in the expanded or depleted populations.

**Comment by mahati-acog** [comment]
Thanks a lot for your response.
