### ISSUE TITLE
shape error

### ISSUE THREAD

**Issue by hmbaghdassarian** [immunogenomics/cna#7]
Hi, 

I'm trying to implement your pipeline based on the tutorial on my single-cell data. I get the following error: "ValueError: Shape of passed values is (41874, 5), indices imply (41874, 10)" when running the command "res = cna.tl.association(d,                   d.samplem.case)". 

From my understanding: this error is because of line 189-191 of the tools/_nam.py. script Specifically, I only have five samples (five rows in d.samplem), and line 158 of this script sets npcs to 10. This causes an error where it's trying to create 10 PC columns when only 5 are available in the V array.  

Please let me know if you need more information or whether I am doing something wrong on my end. 

Thanks and excited to further try your tool!

**Comment by yakirr** [comment]
Dear Hratch,

Thank you for your interest! We agree with you assessment of the code, and we're working on uploading a fix for this bug as soon as we can.

Separately, I want to mention that with 5 samples you may not get very good results with CNA. I would take whatever comes out with a grain of salt and not plan on interpreting anything beyond NAM PC1.

We'll update you and close the issue once we've uploaded the fix.

**Comment by hmbaghdassarian** [comment]
Great, thank you! And thanks for the information

**Comment by yakirr** [comment]
Dear Hratch, @rumker just uploaded a fix for this bug and we have pushed it to pypi. So updating cna or re-cloning the repo should do the trick. Let us know if it doesn't!
