### ISSUE TITLE
Troubles with library import

### ISSUE THREAD

**Issue by serjisa** [immunogenomics/cna#8]
Hi!

I installed cna via pip using the following command: `pip3 install cna` There were no warnings or errors. But after it, I try to import this package and I get this:
```
>>> import cna
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/my_user/.local/lib/python3.6/site-packages/cna/__init__.py", line 1, in <module>
    from . import tools as tl
  File "/home/my_user/.local/lib/python3.6/site-packages/cna/tools/__init__.py", line 2, in <module>
    from ._association import association
  File "/home/my_user/.local/lib/python3.6/site-packages/cna/tools/_association.py", line 6, in <module>
    import cna.tools._stats as stats
AttributeError: module 'cna' has no attribute 'tools'
```
What should I do to fix this bug? This problem doesn't reproduce on a different server with Python 3.7.5.

**Comment by yakirr** [comment]
Hi @serjisa, we're not sure why this error is happening. Could you send us the python version that's causing the difficulty? Thank you!

**Comment by serjisa** [comment]
It's Python 3.6.9

**Comment by yakirr** [comment]
Sergey,

We were able to reproduce this error with that python version. We'll look
into whether a bugfix is possible; in the meantime, it seems python 3.7 is
the way to go. Thank you for bringing this to our attention!

**Comment by yakirr** [comment]
Sergey, we just uploaded a bugfix, it's cna version 0.1.3. Let us know if you have issues with it.
